#!/bin/bash

if [ $# -ne 1 ]
then
	echo "need one argument"
else
if [ $1 = "get" ]
then
	cd ~/projects/bots/"Emoji Generator"
	py emoji_pasta.py
	rm emoji.txt
	cd - > /dev/null
	echo "emoji pasta grabbed"
elif [ $1 = "gen" ]
then
	cd ~/projects/bots/"Emoji Generator"
	py emoji_markov.py
	rm emoji.txt
	cd - > /dev/null
	echo "emoji pasta generated"
elif [ $1 = "train" ]
then
	cd ~/projects/bots/"Emoji Generator"
	py emoji_markov.py 'train'
	rm emoji.txt
	cd - > /dev/null
	echo "emoji pasta trained"
else
	echo "not a valid command"
fi
fi